apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myimage-dev
nameSuffix: -dev

resources:
  - ../../base

patches:
  - path: replica-patch.yaml
  - path: service-patch.yaml

images:
  - name: islamatc/myimage
    newTag: v1.5

labels:
  - pairs:
      environment: dev
    includeSelectors: true
