apiVersion: apps/v1
kind: Deployment
metadata:
  name: myimage
  labels:
    app.kubernetes.io/name: myimage
    app.kubernetes.io/part-of: argocd-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: myimage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myimage
        app.kubernetes.io/part-of: argocd-learning
    spec:
      containers:
        - name: myimage
          image: islamatc/myimage:v1.5
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
